# Generated by Django 5.2.7 on 2025-12-30 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0039_remove_scraper_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bid amount', max_digits=20)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Current rank (1st, 2nd, 3rd, etc.)', null=True)),
                ('is_winning', models.BooleanField(default=False, help_text='True if this is currently the lowest bid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['amount', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReverseAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Auction title/name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what is being requested')),
                ('starting_price', models.DecimalField(decimal_places=2, help_text='Maximum price (ceiling)', max_digits=20)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Hidden minimum price below which contract is guaranteed', max_digits=20, null=True)),
                ('deadline', models.DateTimeField(help_text='When the auction closes')),
                ('minimum_decrement', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount by which a bid must be lower than previous', max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('extended_count', models.PositiveIntegerField(default=0, help_text='Number of times deadline was extended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auctions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='products.category')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='auctions.bid')),
            ],
            options={
                'verbose_name': 'Reverse Auction',
                'verbose_name_plural': 'Reverse Auctions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.reverseauction'),
        ),
        migrations.CreateModel(
            name='AuctionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_invitations', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='auctions.reverseauction')),
            ],
            options={
                'verbose_name': 'Auction Invitation',
                'verbose_name_plural': 'Auction Invitations',
            },
        ),
        migrations.AddIndex(
            model_name='reverseauction',
            index=models.Index(fields=['status', 'deadline'], name='auctions_re_status_380f61_idx'),
        ),
        migrations.AddIndex(
            model_name='reverseauction',
            index=models.Index(fields=['buyer', '-created_at'], name='auctions_re_buyer_i_155bff_idx'),
        ),
        migrations.AddIndex(
            model_name='reverseauction',
            index=models.Index(fields=['category', 'status'], name='auctions_re_categor_d5004e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'amount'], name='auctions_bi_auction_bac253_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['supplier', '-created_at'], name='auctions_bi_supplie_5402da_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'supplier'], name='auctions_bi_auction_648de5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='auctioninvitation',
            index=models.Index(fields=['supplier', '-invited_at'], name='auctions_au_supplie_ac5142_idx'),
        ),
        migrations.AddIndex(
            model_name='auctioninvitation',
            index=models.Index(fields=['auction', 'supplier'], name='auctions_au_auction_a497e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auctioninvitation',
            unique_together={('auction', 'supplier')},
        ),
    ]
