# Generated by Django 5.2.7 on 2025-12-18 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0037_remove_subcategoryfeaturetemplate_unique_subcategory_feature_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDepositPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=5000000, help_text='Amount in Toman', max_digits=12)),
                ('track_id', models.CharField(db_index=True, help_text='Zibal track ID', max_length=100, unique=True)),
                ('order_id', models.CharField(default=uuid.uuid4, help_text='Internal order ID', max_length=100, unique=True)),
                ('ref_number', models.CharField(blank=True, help_text='Zibal reference number', max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, help_text='Masked card number', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='zibal', help_text='Payment gateway used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zibal_response', models.JSONField(blank=True, help_text='Full response from Zibal', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_deposit_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Deposit Payment',
                'verbose_name_plural': 'Auction Deposit Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('request_type', models.CharField(choices=[('free', 'Free Request'), ('verified', 'Verified Request (Paid Deposit)')], default='free', max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=5000000, help_text='Deposit amount in Toman', max_digits=12)),
                ('deposit_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('held_in_escrow', 'Held in Escrow'), ('forfeited', 'Forfeited'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('auction_style', models.CharField(choices=[('sealed', 'Sealed Bid'), ('live_reverse', 'Live Reverse Auction')], default='sealed', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(help_text="Buyer's need explanation")),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='Filled from SubcategoryFeatureTemplate')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_requests', to=settings.AUTH_USER_MODEL)),
                ('deposit_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_request', to='auctions.auctiondepositpayment')),
                ('product', models.ForeignKey(blank=True, help_text='Starting point product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_requests', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_auctions', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(help_text='For feature templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_requests', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Auction Request',
                'verbose_name_plural': 'Auction Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_reports', to=settings.AUTH_USER_MODEL)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='auctions.auctionrequest')),
            ],
            options={
                'verbose_name': 'Auction Report',
                'verbose_name_plural': 'Auction Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auctions.auctionrequest')),
            ],
            options={
                'verbose_name': 'Auction Photo',
                'verbose_name_plural': 'Auction Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='auction_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auctions.auctionrequest')),
            ],
            options={
                'verbose_name': 'Auction Document',
                'verbose_name_plural': 'Auction Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='auctiondepositpayment',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_payment_detail', to='auctions.auctionrequest'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('technical_compliance', models.JSONField(default=dict, help_text='Filled from SubcategoryFeatureTemplate')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, help_text='Final ranking in auction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionrequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['price', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auctionrequest',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='auctions.bid'),
        ),
        migrations.CreateModel(
            name='AuctionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('auction_published', 'Auction Published'), ('bid_received', 'Bid Received'), ('auction_closed', 'Auction Closed'), ('deposit_forfeiture_warning', 'Deposit Forfeiture Warning'), ('deposit_forfeited', 'Deposit Forfeited'), ('auction_approved', 'Auction Approved'), ('auction_rejected', 'Auction Rejected')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_notifications', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auctions.auctionrequest')),
            ],
            options={
                'verbose_name': 'Auction Notification',
                'verbose_name_plural': 'Auction Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='auctions_au_user_id_506dce_idx'), models.Index(fields=['auction', '-created_at'], name='auctions_au_auction_d1e448_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auctiondepositpayment',
            index=models.Index(fields=['user', '-created_at'], name='auctions_au_user_id_87dd94_idx'),
        ),
        migrations.AddIndex(
            model_name='auctiondepositpayment',
            index=models.Index(fields=['status', '-created_at'], name='auctions_au_status_54fe0f_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'price'], name='auctions_bi_auction_70a2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['seller', '-created_at'], name='auctions_bi_seller__c834eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'seller')},
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['buyer', '-created_at'], name='auctions_au_buyer_i_0a3b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['status', '-created_at'], name='auctions_au_status_01a229_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['subcategory', 'status'], name='auctions_au_subcate_ffc3b4_idx'),
        ),
    ]
