# Generated by Django 5.2.7 on 2025-12-16 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(db_index=True, help_text='مسیر قدیمی که باید به مسیر جدید هدایت شود (مثال: /old-page)', max_length=500, unique=True, verbose_name='از مسیر')),
                ('to_path', models.CharField(help_text='مسیر جدید که باید به آن هدایت شود (مثال: /new-page یا https://example.com/page)', max_length=500, verbose_name='به مسیر')),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent Redirect'), ('302', '302 Temporary Redirect')], default='301', help_text='301 برای هدایت دائمی (بهتر برای SEO)، 302 برای هدایت موقت', max_length=3, verbose_name='نوع هدایت')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، این هدایت اعمال نخواهد شد', verbose_name='فعال')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی درباره این هدایت', null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'هدایت URL',
                'verbose_name_plural': 'هدایت\u200cهای URL',
                'db_table': 'pages_redirect',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_path', 'is_active'], name='pages_redir_from_pa_321426_idx')],
            },
        ),
    ]
