# Generated by Django 5.2.7 on 2025-12-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_redirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-created_at'], 'verbose_name': 'URL Redirect', 'verbose_name_plural': 'URL Redirects'},
        ),
    ]
