# Generated by Django 5.2.7 on 2025-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_redirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={
                'db_table': 'pages_redirect',
                'ordering': ['-created_at'],
                'verbose_name': 'URL Redirect',
                'verbose_name_plural': 'URL Redirects',
            },
        ),
    ]

