# Generated by Django 5.2.7 on 2025-12-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_shortlink_shortlinkclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'لینک کوتاه', 'verbose_name_plural': 'لینکهای کوتاه'},
        ),
        migrations.AlterModelOptions(
            name='shortlinkclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'کلیک لینک', 'verbose_name_plural': 'کلیکهای لینک'},
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='campaign_name',
            field=models.CharField(blank=True, help_text='نام کمپین برای شناسایی راحتتر', max_length=200, null=True, verbose_name='نام کمپین'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='اگر غیرفعال باشد، لینک کار نمیکند', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='shortlinkclick',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='آیپی'),
        ),
    ]
