# Generated by Django 4.2.25 on 2025-10-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorprofile_about_vendorprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Buyer Profile', 'verbose_name_plural': 'Buyer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='sellerad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier Advertisement', 'verbose_name_plural': 'Supplier Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='selleradimage',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Supplier Ad Image', 'verbose_name_plural': 'Supplier Ad Images'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'verbose_name': 'Supplier Profile', 'verbose_name_plural': 'Supplier Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Supplier'), ('both', 'Both')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin as supplier'),
        ),
    ]
