# Generated by Django 4.2.25 on 2025-10-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_sellerad_vendorprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='about',
            field=models.TextField(blank=True, help_text='About the supplier/company', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of the supplier', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='history',
            field=models.TextField(blank=True, help_text='Company history and background', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='successful_projects',
            field=models.TextField(blank=True, help_text='List of successful projects', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='work_resume',
            field=models.TextField(blank=True, help_text='Work experience and resume', null=True),
        ),
        migrations.CreateModel(
            name='SupplierComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Approved by admin')),
                ('supplier_reply', models.TextField(blank=True, null=True)),
                ('supplier_replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.vendorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Comment',
                'verbose_name_plural': 'Supplier Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
