# Generated by Django 5.2.7 on 2025-11-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='awards',
            field=models.JSONField(blank=True, help_text='List of awards/achievements', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Hero banner for supplier page', null=True, upload_to='vendor_banners/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='brand_color_primary',
            field=models.CharField(blank=True, help_text='Primary brand color (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='brand_color_secondary',
            field=models.CharField(blank=True, help_text='Secondary brand color (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='certifications',
            field=models.JSONField(blank=True, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of employees', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='slogan',
            field=models.CharField(blank=True, help_text='Company slogan/tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='social_media',
            field=models.JSONField(blank=True, help_text='Social media links', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_url',
            field=models.URLField(blank=True, help_text='Company introduction video URL', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, help_text='Year company was founded', null=True),
        ),
        migrations.CreateModel(
            name='SupplierContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text="Sender's name", max_length=200)),
                ('sender_email', models.EmailField(help_text="Sender's email", max_length=254)),
                ('sender_phone', models.CharField(blank=True, help_text="Sender's phone", max_length=20, null=True)),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='users.vendorprofile')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project/portfolio title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('image', models.ImageField(help_text='Project image', upload_to='portfolio_images/')),
                ('project_date', models.DateField(blank=True, help_text='Date of project', null=True)),
                ('client_name', models.CharField(blank=True, help_text='Client name (optional)', max_length=200, null=True)),
                ('category', models.CharField(blank=True, help_text='Portfolio category', max_length=100, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured project flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='users.vendorprofile')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['sort_order', '-project_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Member name', max_length=200)),
                ('position', models.CharField(help_text='Job title', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Member photo', null=True, upload_to='team_photos/')),
                ('bio', models.TextField(blank=True, help_text='Short bio', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='users.vendorprofile')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
