# Generated by Django 5.2.7 on 2025-11-20 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendorprofile_awards_vendorprofile_banner_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Phone number (when user is not authenticated)', max_length=20)),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('transaction', 'Transaction')], help_text='Purpose of the OTP', max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Whether the OTP has been used')),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('user', models.ForeignKey(blank=True, help_text='User (nullable for phone-based OTP)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='users_otp_phone_86cf13_idx'), models.Index(fields=['user', 'purpose', 'is_used'], name='users_otp_user_id_eb7a7d_idx'), models.Index(fields=['expires_at'], name='users_otp_expires_8f43b7_idx')],
            },
        ),
    ]
