# Generated by Django 4.2.27 on 2025-12-16 08:39
# Updated to be idempotent - handles missing indexes and columns gracefully

from django.db import migrations, models, connection


def rename_indexes_conditionally(apps, schema_editor):
    """
    Conditionally rename indexes only if they exist.
    This makes the migration idempotent and safe to run multiple times.
    """
    if connection.vendor != 'postgresql':
        return
    
    with connection.cursor() as cursor:
        # List of (old_name, new_name) index renames
        index_renames = [
            ('users_conta_note_contact_idx', 'users_conta_contact_cc7c9b_idx'),
            ('users_conta_note_seller_idx', 'users_conta_seller__6aa312_idx'),
            ('users_conta_task_seller_idx', 'users_conta_seller__827342_idx'),
            ('users_conta_task_contact_idx', 'users_conta_contact_c2ee35_idx'),
            ('users_conta_due_dat_idx', 'users_conta_due_dat_3bd16a_idx'),
            ('users_selle_seller_i_idx', 'users_selle_seller__f6671c_idx'),
            ('users_selle_phone_idx', 'users_selle_phone_7e9e71_idx'),
            ('users_selle_email_idx', 'users_selle_email_159c06_idx'),
        ]
        
        for old_name, new_name in index_renames:
            # Check if old index exists and new index doesn't
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                ) AND NOT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
            """, [old_name, new_name])
            
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}"')


def add_monthly_price_rial_conditionally(apps, schema_editor):
    """
    Conditionally add monthly_price_rial column only if it doesn't exist.
    This makes the migration idempotent.
    """
    if connection.vendor != 'postgresql':
        return
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'users_pricingtier' 
                AND column_name = 'monthly_price_rial'
            )
        """)
        
        if not cursor.fetchone()[0]:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE users_pricingtier 
                ADD COLUMN monthly_price_rial NUMERIC(12, 0) NULL
            """)


def reverse_rename_indexes(apps, schema_editor):
    """Reverse: Rename indexes back (if needed)"""
    pass


def reverse_add_monthly_price_rial(apps, schema_editor):
    """Reverse: Remove the column"""
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE users_pricingtier 
                DROP COLUMN IF EXISTS monthly_price_rial
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_crm_models'),
    ]

    operations = [
        # Conditionally rename indexes (only if they exist)
        # Use SeparateDatabaseAndState so Django knows these operations were done
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_conditionally, reverse_rename_indexes),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='contactnote',
                    new_name='users_conta_contact_cc7c9b_idx',
                    old_name='users_conta_note_contact_idx',
                ),
                migrations.RenameIndex(
                    model_name='contactnote',
                    new_name='users_conta_seller__6aa312_idx',
                    old_name='users_conta_note_seller_idx',
                ),
                migrations.RenameIndex(
                    model_name='contacttask',
                    new_name='users_conta_seller__827342_idx',
                    old_name='users_conta_task_seller_idx',
                ),
                migrations.RenameIndex(
                    model_name='contacttask',
                    new_name='users_conta_contact_c2ee35_idx',
                    old_name='users_conta_task_contact_idx',
                ),
                migrations.RenameIndex(
                    model_name='contacttask',
                    new_name='users_conta_due_dat_3bd16a_idx',
                    old_name='users_conta_due_dat_idx',
                ),
                migrations.RenameIndex(
                    model_name='sellercontact',
                    new_name='users_selle_seller__f6671c_idx',
                    old_name='users_selle_seller_i_idx',
                ),
                migrations.RenameIndex(
                    model_name='sellercontact',
                    new_name='users_selle_phone_7e9e71_idx',
                    old_name='users_selle_phone_idx',
                ),
                migrations.RenameIndex(
                    model_name='sellercontact',
                    new_name='users_selle_email_159c06_idx',
                    old_name='users_selle_email_idx',
                ),
            ],
        ),
        
        # Conditionally add monthly_price_rial column (only if it doesn't exist)
        # Use SeparateDatabaseAndState to handle DB operation separately from Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_monthly_price_rial_conditionally, reverse_add_monthly_price_rial),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='pricingtier',
                    name='monthly_price_rial',
                    field=models.DecimalField(blank=True, decimal_places=0, help_text='Monthly subscription price in Rial for Zibal payment gateway', max_digits=12, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Auto-renew subscription on expiry'),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='expiry_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When expiry reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price in Toman (if applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercomment',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for moderation'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True),
        ),
    ]
