# Generated by Django 4.2.27 on 2025-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_crm_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactnote',
            new_name='users_conta_contact_cc7c9b_idx',
            old_name='users_conta_note_contact_idx',
        ),
        migrations.RenameIndex(
            model_name='contactnote',
            new_name='users_conta_seller__6aa312_idx',
            old_name='users_conta_note_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='contacttask',
            new_name='users_conta_seller__827342_idx',
            old_name='users_conta_task_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='contacttask',
            new_name='users_conta_contact_c2ee35_idx',
            old_name='users_conta_task_contact_idx',
        ),
        migrations.RenameIndex(
            model_name='contacttask',
            new_name='users_conta_due_dat_3bd16a_idx',
            old_name='users_conta_due_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='sellercontact',
            new_name='users_selle_seller__f6671c_idx',
            old_name='users_selle_seller_i_idx',
        ),
        migrations.RenameIndex(
            model_name='sellercontact',
            new_name='users_selle_phone_7e9e71_idx',
            old_name='users_selle_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='sellercontact',
            new_name='users_selle_email_159c06_idx',
            old_name='users_selle_email_idx',
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='monthly_price_rial',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monthly subscription price in Rial for Zibal payment gateway', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Auto-renew subscription on expiry'),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='expiry_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When expiry reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price in Toman (if applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercomment',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for moderation'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True),
        ),
    ]
