# Generated by Django 5.2.7 on 2025-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_users_conta_note_contact_idx_users_conta_contact_cc7c9b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingtier',
            name='monthly_price_rial',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='suppliercomment',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='suppliercomment',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='contact_phone_landline',
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price (if applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
