#!/bin/bash
# Quick reference script for creating staging apps in CapRover
# This script shows the commands you need to run, but apps must be created via CapRover dashboard

echo "=========================================="
echo "📋 Staging Apps Setup Instructions"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: Apps must be created via CapRover Dashboard"
echo "   This script only shows what you need to do."
echo ""
echo "🔗 CapRover Dashboard: https://captain.indexo.ir"
echo ""
echo "=========================================="
echo "1️⃣  CREATE BACKEND APP"
echo "=========================================="
echo ""
echo "1. Go to: https://captain.indexo.ir"
echo "2. Navigate to: Apps → Create New App"
echo "3. App Name: multivendor-backend-staging"
echo "   (or match your CAPROVER_BACKEND_STAGING_APP_NAME secret)"
echo "4. Has Persistent Data: ✅ YES"
echo "5. Enable HTTPS: ✅ YES"
echo "6. Add custom domains:"
echo "   - staging-api.indexo.ir"
echo "   - staging-backend.indexo.ir"
echo ""
echo "7. After creating, go to App Configs and add environment variables:"
echo "   (See: caprover-env-backend-staging.txt)"
echo ""
echo "=========================================="
echo "2️⃣  CREATE FRONTEND APP"
echo "=========================================="
echo ""
echo "1. Go to: https://captain.indexo.ir"
echo "2. Navigate to: Apps → Create New App"
echo "3. App Name: multivendor-frontend-staging"
echo "   (or match your CAPROVER_FRONTEND_STAGING_APP_NAME secret)"
echo "4. Has Persistent Data: ❌ NO"
echo "5. Enable HTTPS: ✅ YES"
echo "6. Add custom domain:"
echo "   - staging.indexo.ir"
echo ""
echo "7. After creating, go to App Configs and add environment variables:"
echo "   (See: caprover-env-frontend-staging.txt)"
echo ""
echo "=========================================="
echo "3️⃣  VERIFY GITHUB SECRETS"
echo "=========================================="
echo ""
echo "Make sure these secrets are set in GitHub:"
echo "   - CAPROVER_URL = https://captain.indexo.ir"
echo "   - CAPROVER_PASSWORD = <your-caprover-password>"
echo "   - CAPROVER_BACKEND_STAGING_APP_NAME = multivendor-backend-staging"
echo "   - CAPROVER_FRONTEND_STAGING_APP_NAME = multivendor-frontend-staging"
echo ""
echo "GitHub → Settings → Secrets and variables → Actions"
echo ""
echo "=========================================="
echo "4️⃣  RETRY DEPLOYMENT"
echo "=========================================="
echo ""
echo "After creating apps and setting secrets:"
echo "   - Re-run the failed workflow in GitHub Actions, OR"
echo "   - Push another commit to staging branch"
echo ""
echo "=========================================="






