services:
  # --- Backend (Django) ---
  backend:
    image: ghcr.io/YOUR_GITHUB_USERNAME/indexo-backend:staging  # We will build this image later
    container_name: indexo_backend_staging
    restart: always
    command: sh -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_volume_staging:/app/media
      - static_volume_staging:/app/static
    env_file:
      - .env.staging  # IMPORTANT: You need a separate env file
    networks:
      - docker-deploy_multivendor_network 
      - internal_staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-staging.rule=Host(`api.staging.indexo.ir`)"
      - "traefik.http.routers.backend-staging.entrypoints=websecure"
      - "traefik.http.routers.backend-staging.tls.certresolver=myresolver"
      - "traefik.http.services.backend-staging.loadbalancer.server.port=8000"

  # --- Frontend (Nuxt) ---
  frontend:
    image: ghcr.io/YOUR_GITHUB_USERNAME/indexo-frontend:staging
    container_name: indexo_frontend_staging
    restart: always
    networks:
      - docker-deploy_multivendor_network 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-staging.rule=Host(`staging.indexo.ir`)"
      - "traefik.http.routers.frontend-staging.entrypoints=websecure"
      - "traefik.http.routers.frontend-staging.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-staging.loadbalancer.server.port=3000"

  # --- Database (Postgres Staging) ---
  db:
    image: postgres:15
    container_name: indexo_db_staging
    restart: always
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    env_file:
      - .env.staging
    networks:
      - internal_staging

networks:
  docker-deploy_multivendor_network:  # <--- The real name of your network
    external: true
  internal_staging:
    driver: bridge

volumes:
  postgres_data_staging:  # Separate data from Prod!
  media_volume_staging:
  static_volume_staging:
