#!/bin/bash
# Fix script for nginx-backend 502 errors
# This script updates nginx configuration to fix backend connectivity issues

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Nginx-Backend Connection Fix${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if nginx container exists
if ! docker ps --filter "name=multivendor_nginx" --format "{{.Names}}" | grep -q multivendor_nginx; then
    echo -e "${RED}✗ Nginx container not found${NC}"
    echo "   Please start nginx first: docker-compose up -d nginx"
    exit 1
fi

# Check if backend container exists
if ! docker ps --filter "name=multivendor_backend" --format "{{.Names}}" | grep -q multivendor_backend; then
    echo -e "${RED}✗ Backend container not found${NC}"
    echo "   Please start backend first: docker-compose up -d backend"
    exit 1
fi

# Get backend IP address
echo -e "${YELLOW}[1/4] Getting backend IP address...${NC}"
BACKEND_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' multivendor_backend 2>/dev/null)

if [ -z "$BACKEND_IP" ]; then
    echo -e "${RED}✗ Could not determine backend IP address${NC}"
    exit 1
fi

echo "   Backend IP: $BACKEND_IP"

# Create improved nginx config with fallback
echo -e "${YELLOW}[2/4] Creating improved nginx configuration...${NC}"

# Read current nginx config
CURRENT_CONFIG=$(docker exec multivendor_nginx cat /etc/nginx/conf.d/default.conf 2>/dev/null || echo "")

# Create backup
echo -e "${YELLOW}[3/4] Creating backup of current nginx config...${NC}"
docker exec multivendor_nginx cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.backup 2>/dev/null || true

# Create improved config with explicit backend IP as fallback
cat > /tmp/nginx-fixed.conf << EOF
# Improved nginx configuration with backend connectivity fixes
# Generated by fix-nginx-backend.sh

upstream backend {
    # Try service name first (works in docker-compose)
    server backend:8000 max_fails=3 fail_timeout=30s;
    # Fallback to container IP if DNS fails
    server $BACKEND_IP:8000 backup;
}

upstream frontend {
    server frontend:3000 max_fails=3 fail_timeout=30s;
}

# Add resolver for dynamic DNS (if needed)
resolver 127.0.0.11 valid=30s;

server {
    listen 80;
    server_name _;
    client_max_body_size 100M;

    # Increase timeouts for slow backend responses
    proxy_connect_timeout 75s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;

    # Static files
    location /static/ {
        alias /usr/share/nginx/html/staticfiles/;
        expires 365d;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    location /staticfiles/ {
        alias /usr/share/nginx/html/staticfiles/;
        expires 365d;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    # Media files
    location /media/ {
        alias /usr/share/nginx/html/media/;
        expires 90d;
        access_log off;
        add_header Cache-Control "public";
    }

    # API requests - with improved error handling
    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Error handling
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
        proxy_next_upstream_tries 2;
        proxy_next_upstream_timeout 10s;
        
        # Timeouts
        proxy_connect_timeout 75s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        
        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
        proxy_busy_buffers_size 8k;
    }

    # Admin panel
    location /admin/ {
        proxy_pass http://backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }

    # WebSocket
    location /ws/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_buffering off;
    }

    # Health check
    location /health/ {
        proxy_pass http://backend;
        access_log off;
    }

    # Root - proxy to frontend
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_buffering off;
    }
}
EOF

# Copy new config to nginx container
echo -e "${YELLOW}[4/4] Applying new nginx configuration...${NC}"
docker cp /tmp/nginx-fixed.conf multivendor_nginx:/etc/nginx/conf.d/default.conf

# Test nginx configuration
if docker exec multivendor_nginx nginx -t; then
    echo -e "${GREEN}✓ Nginx configuration is valid${NC}"
    
    # Reload nginx
    echo "   Reloading nginx..."
    docker exec multivendor_nginx nginx -s reload
    
    echo ""
    echo -e "${GREEN}✓ Nginx configuration updated and reloaded!${NC}"
    echo ""
    echo "The new configuration includes:"
    echo "  - Explicit backend upstream with IP fallback"
    echo "  - Improved error handling and retries"
    echo "  - Increased timeouts"
    echo "  - Better proxy headers"
    echo ""
    echo "Test the connection:"
    echo "  curl http://localhost/api/health/"
    echo "  docker logs multivendor_nginx"
else
    echo -e "${RED}✗ Nginx configuration has errors!${NC}"
    echo "   Restoring backup..."
    docker exec multivendor_nginx cp /etc/nginx/conf.d/default.conf.backup /etc/nginx/conf.d/default.conf 2>/dev/null || true
    exit 1
fi

# Cleanup
rm -f /tmp/nginx-fixed.conf

echo ""
echo -e "${GREEN}Fix completed!${NC}"

