# Generated by Django 5.2.7 on 2025-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='reason',
            field=models.CharField(choices=[('login', 'Login'), ('product_save', 'Product Save'), ('profile_update', 'Profile Update'), ('mini_site', 'Mini Website Update'), ('fast_response', 'Fast Order Response'), ('tutorial', 'Watched Tutorial'), ('badge', 'Badge Earned'), ('section_completion', 'Section Completion'), ('custom', 'Custom Action')], default='custom', max_length=30),
        ),
    ]
