# Generated by Django 5.2.7 on 2025-12-09 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_pointshistory_reason'),
        ('users', '0007_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierengagement',
            name='endorsements_received',
            field=models.PositiveIntegerField(default=0, help_text='Number of peer endorsements received'),
        ),
        migrations.AddField(
            model_name='supplierengagement',
            name='positive_reviews_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of positive reviews (rating >= 4)'),
        ),
        migrations.AddField(
            model_name='supplierengagement',
            name='reputation_score',
            field=models.FloatField(default=0.0, help_text='Calculated reputation score based on endorsements, reviews, and response speed'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='reason',
            field=models.CharField(choices=[('login', 'Login'), ('product_save', 'Product Save'), ('profile_update', 'Profile Update'), ('mini_site', 'Mini Website Update'), ('fast_response', 'Fast Order Response'), ('tutorial', 'Watched Tutorial'), ('badge', 'Badge Earned'), ('section_completion', 'Section Completion'), ('peer_invitation', 'Peer Invitation'), ('endorsement_received', 'Endorsement Received'), ('custom', 'Custom Action')], default='custom', max_length=30),
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed', models.ForeignKey(help_text='Vendor profile that received the endorsement (inviter)', on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to='users.vendorprofile')),
                ('endorser', models.ForeignKey(help_text='User who gave the endorsement (invited user)', on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endorsed', 'created_at'], name='gamificatio_endorse_aa1813_idx')],
                'unique_together': {('endorser', 'endorsed')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, help_text='Unique invitation code', max_length=50, unique=True)),
                ('invited_email', models.EmailField(blank=True, help_text='Email of invited user', max_length=254, null=True)),
                ('invited_phone', models.CharField(blank=True, help_text='Phone number of invited user', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_user', models.ForeignKey(blank=True, help_text='User who registered using this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='users.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invite_code'], name='gamificatio_invite__517957_idx'), models.Index(fields=['inviter', 'status'], name='gamificatio_inviter_cc23ae_idx')],
            },
        ),
    ]
