# Generated by Django 5.2.7 on 2025-12-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_create_initial_badges'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='gamificatio_invite__517957_idx',
            old_name='gamificatio_invite_code_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='gamificatio_status_2126a2_idx',
            old_name='gamificatio_status_created_idx',
        ),
    ]
