# Generated by Django 5.2.7 on 2025-12-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_sellerinsight'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitationblocklog',
            new_name='gamificatio_reason_548214_idx',
            old_name='gamificatio_reason_57b697_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewflaglog',
            new_name='gamificatio_reason_556742_idx',
            old_name='gamificatio_reason_35c6f5_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerinsight',
            new_name='gamificatio_created_d03c01_idx',
            old_name='gamificati_created_0adf81_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerinsightcomment',
            new_name='gamificatio_insight_fce893_idx',
            old_name='gamificati_insight__55a5a4_idx',
        ),
        migrations.AlterField(
            model_name='sellerinsight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellerinsightcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
