# Generated by Django 4.2.26 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_increase_price_field_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_responded_at",
            field=models.DateTimeField(
                blank=True, help_text="When supplier first responded", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="first_viewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When supplier first opened the order", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="response_points_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="response_speed_bucket",
            field=models.CharField(
                blank=True,
                help_text="Speed category (sub_1h, sub_4h, sub_24h)",
                max_length=20,
                null=True,
            ),
        ),
    ]
