# Generated by Django 5.2.7 on 2025-11-21 12:00

from django.db import migrations, models, connection


def add_fields_if_not_exist(apps, schema_editor):
    """
    Conditionally add fields if they don't exist.
    This handles both fresh databases and databases that already have these columns.
    """
    if connection.vendor == 'postgresql':
        # PostgreSQL: Use proper conditional logic
        schema_editor.execute("""
            DO $$
            BEGIN
                -- Add first_responded_at if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_responded_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_responded_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;

                -- Add first_viewed_at if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_viewed_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_viewed_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;

                -- Add response_points_awarded if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_points_awarded'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_points_awarded BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;

                -- Add response_speed_bucket if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_speed_bucket'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_speed_bucket VARCHAR(20) NULL;
                END IF;
            END $$;
        """)
    else:
        # SQLite: Check each column individually
        cursor = connection.cursor()
        cursor.execute("PRAGMA table_info(orders_order)")
        existing_columns = {row[1] for row in cursor.fetchall()}
        
        if 'first_responded_at' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN first_responded_at DATETIME NULL")
        if 'first_viewed_at' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN first_viewed_at DATETIME NULL")
        if 'response_points_awarded' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN response_points_awarded BOOLEAN DEFAULT 0 NOT NULL")
        if 'response_speed_bucket' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN response_speed_bucket VARCHAR(20) NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_lead_source_and_suppliers'),
    ]

    operations = [
        # Separate database operations from state changes
        # This allows us to conditionally create columns while always updating Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Add columns only if they don't exist (idempotent)
                migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
            ],
            state_operations=[
                # Always update Django's migration state
                migrations.AddField(
                    model_name='order',
                    name='first_responded_at',
                    field=models.DateTimeField(blank=True, null=True, help_text='When supplier first responded'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='first_viewed_at',
                    field=models.DateTimeField(blank=True, null=True, help_text='When supplier first opened the order'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='response_points_awarded',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='order',
                    name='response_speed_bucket',
                    field=models.CharField(max_length=20, blank=True, null=True, help_text='Speed category (sub_1h, sub_4h, sub_24h)'),
                ),
            ],
        ),
    ]

