# Generated by Django 4.2.26 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_lead_source_and_suppliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_responded_at",
            field=models.DateTimeField(
                blank=True, help_text="When supplier first responded", null=True
            ),
        ),
    ]