# Generated by Django 4.2.26 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_lead_source_and_suppliers"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_responded_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_responded_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE orders_order DROP COLUMN IF EXISTS first_responded_at;
            """,
        ),
    ]