# Generated by Django 5.2.7 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_first_responded_at_order_first_viewed_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Add first_viewed_at if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_viewed_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_viewed_at TIMESTAMP WITH TIME ZONE NULL;
                END IF;

                -- Add response_points_awarded if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_points_awarded'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_points_awarded BOOLEAN DEFAULT FALSE;
                END IF;

                -- Add response_speed_bucket if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_speed_bucket'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_speed_bucket VARCHAR(20) NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE orders_order DROP COLUMN IF EXISTS first_viewed_at;
            ALTER TABLE orders_order DROP COLUMN IF EXISTS response_points_awarded;
            ALTER TABLE orders_order DROP COLUMN IF EXISTS response_speed_bucket;
            """,
        ),
    ]