# Generated by Django 5.2.7 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_first_responded_at_order_first_viewed_at_and_more'),
    ]

    operations = [
        # Skip adding first_responded_at since it already exists
        migrations.AddField(
            model_name="order",
            name="first_viewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When supplier first opened the order", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="response_points_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="response_speed_bucket",
            field=models.CharField(
                blank=True,
                help_text="Speed category (sub_1h, sub_4h, sub_24h)",
                max_length=20,
                null=True,
            ),
        ),
    ]