# Generated by Django 5.2.7 on 2025-11-21 09:33

from django.db import migrations, models, connection


def add_order_fields(apps, schema_editor):
    """Add fields only if they don't exist (works for both PostgreSQL and SQLite)"""
    if connection.vendor == 'postgresql':
        # PostgreSQL: Use proper conditional logic
        schema_editor.execute("""
            DO $$
            BEGIN
                -- Add first_responded_at if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_responded_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_responded_at TIMESTAMP WITH TIME ZONE NULL;
                    COMMENT ON COLUMN orders_order.first_responded_at IS 'When supplier first responded';
                END IF;

                -- Add first_viewed_at if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'first_viewed_at'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN first_viewed_at TIMESTAMP WITH TIME ZONE NULL;
                    COMMENT ON COLUMN orders_order.first_viewed_at IS 'When supplier first opened the order';
                END IF;

                -- Add response_points_awarded if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_points_awarded'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_points_awarded BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;

                -- Add response_speed_bucket if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'orders_order' AND column_name = 'response_speed_bucket'
                ) THEN
                    ALTER TABLE orders_order ADD COLUMN response_speed_bucket VARCHAR(20) NULL;
                    COMMENT ON COLUMN orders_order.response_speed_bucket IS 'Speed category (sub_1h, sub_4h, sub_24h)';
                END IF;
            END $$;
        """)
    else:
        # SQLite: Check each column individually
        cursor = connection.cursor()
        cursor.execute("PRAGMA table_info(orders_order)")
        existing_columns = {row[1] for row in cursor.fetchall()}
        
        if 'first_responded_at' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN first_responded_at DATETIME NULL")
        if 'first_viewed_at' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN first_viewed_at DATETIME NULL")
        if 'response_points_awarded' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN response_points_awarded BOOLEAN DEFAULT 0 NOT NULL")
        if 'response_speed_bucket' not in existing_columns:
            schema_editor.execute("ALTER TABLE orders_order ADD COLUMN response_speed_bucket VARCHAR(20) NULL")


def remove_order_fields(apps, schema_editor):
    """Remove fields (no-op for safety - we don't actually want to remove data)"""
    # Don't actually remove columns in reverse migration
    # This is safer for production data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_fix_duplicate_first_responded_at'),
    ]

    operations = [
        migrations.RunPython(add_order_fields, remove_order_fields),
    ]
