# Generated by Django 4.2.25 on 2025-12-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_commission_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordervendorview',
            new_name='orders_orde_vendor__1dd5ab_idx',
            old_name='orders_orde_vendor__c8d667_idx',
        ),
    ]
