# Generated by Django 5.2.7 on 2025-12-22 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_orders_orde_vendor__c8d667_idx_orders_orde_vendor__1dd5ab_idx'),
        ('products', '0038_product_products_pr_vendor__a3dca5_idx_and_more'),
        ('users', '0015_remove_pricingtier_monthly_price_rial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='orders_orde_buyer_i_67c51b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_rfq', 'status', '-created_at'], name='orders_orde_is_rfq_2df6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_rfq', 'is_free', '-created_at'], name='orders_orde_is_rfq_8b6262_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['category', 'is_rfq', 'status'], name='orders_orde_categor_e86122_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['first_viewed_at'], name='orders_orde_first_v_ad38a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['first_responded_at'], name='orders_orde_first_r_35ca92_idx'),
        ),
    ]
