# Generated by Django 4.2.27 on 2025-12-16 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Amount in Rials', max_digits=12)),
                ('track_id', models.CharField(db_index=True, help_text='Zibal track ID', max_length=100, unique=True)),
                ('order_id', models.CharField(default=uuid.uuid4, help_text='Internal order ID', max_length=100, unique=True)),
                ('ref_number', models.CharField(blank=True, help_text='Zibal reference number', max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, help_text='Masked card number', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Verified'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='zibal', help_text='Payment gateway used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was made', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When payment was verified', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zibal_response', models.JSONField(blank=True, help_text='Full response from Zibal', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Subscription Payment',
                'verbose_name_plural': 'Premium Subscription Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment due date (for records)')),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Subtotal in Rials', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, help_text='Tax amount (9% VAT)', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, help_text='Total amount in Rials', max_digits=12)),
                ('invoice_pdf', models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to='invoices/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.premiumsubscriptionpayment')),
            ],
            options={
                'verbose_name': 'Payment Invoice',
                'verbose_name_plural': 'Payment Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='premiumsubscriptionpayment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pr_user_id_fc5479_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumsubscriptionpayment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pr_status_3534a0_idx'),
        ),
    ]
