# Generated by Django 4.2.25 on 2025-12-21 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique discount code (e.g., SUMMER2024)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Campaign name for admin reference', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Campaign description', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount (Toman)')], default='percentage', help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (percentage or fixed Toman)', max_digits=10)),
                ('billing_period', models.CharField(choices=[('all', 'All Periods'), ('monthly', 'Monthly Only'), ('quarterly', 'Quarterly Only'), ('semiannual', 'Semiannual Only'), ('yearly', 'Yearly Only')], default='all', help_text='Which billing periods this discount applies to', max_length=20)),
                ('min_amount_toman', models.DecimalField(decimal_places=0, default=0, help_text='Minimum purchase amount in Toman (0 = no minimum)', max_digits=12)),
                ('max_discount_toman', models.DecimalField(blank=True, decimal_places=0, help_text='Maximum discount amount in Toman (null = no limit)', max_digits=12, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be used (null = unlimited)', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum times a single user can use this code')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used')),
                ('valid_from', models.DateTimeField(help_text='Campaign start date and time')),
                ('valid_until', models.DateTimeField(help_text='Campaign end date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this campaign is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Campaign',
                'verbose_name_plural': 'Discount Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='premiumsubscriptionpayment',
            name='discount_amount_toman',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Discount amount applied in Toman', max_digits=12),
        ),
        migrations.AddField(
            model_name='premiumsubscriptionpayment',
            name='discount_campaign',
            field=models.ForeignKey(blank=True, help_text='Discount campaign used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.discountcampaign'),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount_toman', models.DecimalField(decimal_places=0, help_text='Discount amount applied in Toman', max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.discountcampaign')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='payments.premiumsubscriptionpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['campaign', 'user'], name='payments_di_campaig_e502bd_idx'), models.Index(fields=['user', '-used_at'], name='payments_di_user_id_9a8944_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='discountcampaign',
            index=models.Index(fields=['code', 'is_active'], name='payments_di_code_5dc767_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcampaign',
            index=models.Index(fields=['valid_from', 'valid_until'], name='payments_di_valid_f_e2f0b9_idx'),
        ),
    ]
