# Generated by Django 5.2.7 on 2025-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discountcampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcampaign',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique discount code (e.g., SUMMER2024). Will be stored in uppercase.', max_length=50, unique=True),
        ),
    ]
