# Generated by Django 4.2.25 on 2025-10-15 07:31

from django.db import migrations


def create_default_category(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    
    # Create a default category if it doesn't exist
    default_category, created = Category.objects.get_or_create(
        name='General',
        defaults={'description': 'General category for products without a specific category'}
    )
    
    # Assign the default category to any products that don't have a category
    Product.objects.filter(category__isnull=True).update(category=default_category)


def reverse_create_default_category(apps, schema_editor):
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_category, reverse_create_default_category),
    ]
