# Generated by Django 4.2.25 on 2025-10-16 04:56

from django.db import migrations


def migrate_existing_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    
    for product in Product.objects.filter(image__isnull=False):
        # Create ProductImage from existing product.image
        ProductImage.objects.create(
            product=product,
            image=product.image,
            is_primary=True,
            sort_order=0
        )


def reverse_migrate_images(apps, schema_editor):
    ProductImage = apps.get_model('products', 'ProductImage')
    ProductImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_product_image_model'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_images, reverse_migrate_images),
    ]
