# Generated by Django 4.2.25 on 2025-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_migrate_existing_images'),
    ]

    operations = [
        # Remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
        # Add the new conditional unique constraint
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(
                fields=['product', 'is_primary'],
                condition=models.Q(is_primary=True),
                name='unique_primary_per_product'
            ),
        ),
    ]
