# Generated by Django 4.2.25 on 2025-10-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_fix_unique_constraint'),
    ]

    operations = [
        # Remove all constraints
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_per_product',
        ),
    ]
