# Generated by Django 4.2.25 on 2025-10-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_all_constraints'),
    ]

    operations = [
    ]
