# Generated by Django 4.2.25 on 2025-10-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_remove_product_subcategory_product_subcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the product page to scrape', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scraping failed', null=True)),
                ('scraped_data', models.JSONField(blank=True, help_text='Raw scraped data in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the scraping was processed', null=True)),
                ('created_product', models.ForeignKey(blank=True, help_text='Product created from this scrape job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_job', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier/Company for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to='users.supplier')),
                ('vendor', models.ForeignKey(help_text='Vendor who requested the scrape', on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Scrape Job',
                'verbose_name_plural': 'Product Scrape Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
