# Generated by Django 4.2.25 on 2025-10-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_supplier'),
        ('products', '0022_add_robust_error_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscrapejob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Primary error message if scraping failed', null=True),
        ),
        migrations.CreateModel(
            name='ScrapeJobBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this batch', max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors')], default='pending', max_length=30)),
                ('total_urls', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, help_text='Complete batch report in JSON', null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_batches', to='users.supplier')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrape Job Batch',
                'verbose_name_plural': 'Scrape Job Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productscrapejob',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this job belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='products.scrapejobbatch'),
        ),
    ]
