# Generated by Django 5.2.7 on 2025-11-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_add_og_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for badge (include #)', max_length=7, null=True)),
                ('is_promotional', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_seo_page', models.BooleanField(default=False, help_text='Controls whether this label gets a dedicated landing page')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_h1', models.CharField(blank=True, max_length=140, null=True)),
                ('seo_intro_text', models.TextField(blank=True, null=True)),
                ('seo_faq', models.JSONField(blank=True, help_text='Optional FAQ JSON array (list of {"question": "", "answer": ""})', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='OpenGraph image for SEO pages', null=True, upload_to='label_og_images/')),
                ('schema_markup', models.TextField(blank=True, help_text='Optional JSON-LD markup', null=True)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Label Group',
                'verbose_name_plural': 'Label Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.label'),
        ),
        migrations.CreateModel(
            name='LabelComboSeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_h1', models.CharField(blank=True, max_length=140, null=True)),
                ('seo_intro_text', models.TextField(blank=True, null=True)),
                ('seo_faq', models.JSONField(blank=True, help_text='FAQ entries for combo page', null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='label_combo_og_images/')),
                ('schema_markup', models.TextField(blank=True, null=True)),
                ('is_indexable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='combo_pages', to='products.label')),
            ],
            options={
                'verbose_name': 'Label Combo SEO Page',
                'verbose_name_plural': 'Label Combo SEO Pages',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='label',
            name='label_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='products.labelgroup'),
        ),
    ]
