# Generated by Django 5.2.7 on 2025-11-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_label_labelgroup_product_labels_labelcomboseopage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='labels', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='labelgroup',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Assign this group to subcategories; leave empty to keep it global.', related_name='label_groups', to='products.subcategory'),
        ),
    ]
