# Generated by Django 5.2.7 on 2025-11-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_label_subcategories_labelgroup_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Limit this label to specific categories (leave empty for all categories).', related_name='labels', to='products.category'),
        ),
        migrations.AddField(
            model_name='label',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Limit this label to specific departments (leave empty for all departments).', related_name='labels', to='products.department'),
        ),
    ]
