# Generated by Django 5.2.7 on 2025-11-27 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_add_category_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('in_stock', 'موجود در انبار'), ('made_to_order', 'سفارشی')], help_text='وضعیت موجودی محصول', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'نو'), ('used', 'دست دوم')], help_text='وضعیت محصول (فقط برای محصولات موجود در انبار)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='زمان تحویل به روز کاری (فقط برای محصولات سفارشی)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, choices=[('iran', 'ساخت ایران'), ('imported', 'وارداتی')], help_text='مبدا محصول', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ویژگی', max_length=200)),
                ('value', models.CharField(help_text='مقدار ویژگی', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
