# Generated by Django 4.2.25 on 2025-12-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_add_canonical_url_and_image_alt_text_to_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelManagementProxy',
            fields=[
            ],
            options={
                'verbose_name': 'مدیریت لیبل\u200cهای SEO',
                'verbose_name_plural': 'مدیریت لیبل\u200cهای SEO',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.label',),
        ),
    ]
