# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_subcategory_feature_template'),
    ]

    operations = [
        # This migration was applied to the database but the file was lost
        # Creating a dummy migration to satisfy Django's migration history
        # No operations needed as the changes were already applied
    ]

