# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_subcategory_feature_template'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subcategoryfeaturetemplate',
            name='unique_subcategory_feature_name',
        ),
    ]

