# Generated by Django 5.2.7 on 2025-12-22 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_subcategoryfeaturetemplate_unique_subcategory_feature_name_and_more'),
        ('users', '0015_remove_pricingtier_monthly_price_rial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', '-created_at'], name='products_pr_vendor__a3dca5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status', 'is_active', '-created_at'], name='products_pr_approva_48b69f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'approval_status', 'is_marketplace_hidden'], name='products_pr_is_acti_450abe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['primary_category', 'approval_status', 'is_active'], name='products_pr_primary_d2204c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
    ]
