# Generated by Django 5.2.7 on 2025-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_seo_fields'),
        ('products', '0026_add_og_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='linked_subcategories',
            field=models.ManyToManyField(blank=True, help_text='Select multiple subcategories for this blog category', related_name='blog_categories', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='linked_subcategories',
            field=models.ManyToManyField(blank=True, help_text='Select subcategories for this blog post', related_name='blog_posts', to='products.subcategory'),
        ),
    ]
