# Generated by Django 5.2.7 on 2025-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_linked_subcategories_and_more'),
        ('products', '0026_add_og_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='linked_subcategories',
            field=models.ManyToManyField(blank=True, help_text='Select subcategories for this blog post (from the selected category)', related_name='blog_posts', to='products.subcategory'),
        ),
    ]
