# Generated by Django 4.2.27 on 2025-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_linked_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the featured image (for accessibility and SEO)', max_length=200, null=True),
        ),
    ]
