# Generated by Django 4.2.27 on 2025-12-21 06:38

from django.db import migrations, models
import sms_newsletter.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0037_remove_subcategoryfeaturetemplate_unique_subcategory_feature_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSMSNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='نام شخص تامین\u200cکننده', max_length=200, verbose_name='نام تامین\u200cکننده')),
                ('company_name', models.CharField(help_text='نام شرکت تامین\u200cکننده', max_length=200, verbose_name='نام شرکت')),
                ('phone', models.CharField(blank=True, help_text='شماره تلفن ثابت', max_length=20, null=True, validators=[sms_newsletter.validators.validate_iranian_phone], verbose_name='تلفن')),
                ('mobile', models.CharField(help_text='شماره موبایل (برای ارسال پیامک)', max_length=20, validators=[sms_newsletter.validators.validate_iranian_phone], verbose_name='موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('working_fields', models.ManyToManyField(blank=True, help_text='زمینه\u200cهای کاری تامین\u200cکننده (می\u200cتوانید چند مورد انتخاب کنید)', related_name='supplier_newsletters', to='products.subcategory', verbose_name='زمینه\u200cهای کاری')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده خبرنامه پیامکی',
                'verbose_name_plural': 'تامین\u200cکنندگان خبرنامه پیامکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
