# Generated by Django 4.2.27 on 2025-12-21 07:46

from django.db import migrations, models
import sms_newsletter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sms_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersmsnewsletter',
            name='mobile',
            field=models.CharField(help_text='شماره موبایل (برای ارسال پیامک)', max_length=20, unique=True, validators=[sms_newsletter.validators.validate_iranian_phone], verbose_name='موبایل'),
        ),
    ]
