# Generated by Django 5.2.7 on 2025-12-25 12:57
# Fixed: Made migration more robust to handle table name mismatches

import sms_newsletter.models
from django.db import migrations, models


def safe_alter_field(apps, schema_editor):
    """Safely alter field only if table exists with correct name"""
    db_alias = schema_editor.connection.alias
    Seller = apps.get_model('sms_newsletter', 'Seller')
    
    try:
        table_name = Seller._meta.db_table
        # Expected table name should be sms_newsletter_seller
        expected_table = 'sms_newsletter_seller'
        
        with schema_editor.connection.cursor() as cursor:
            # Check if the correct table exists
            cursor.execute(
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = %s)",
                [expected_table]
            )
            table_exists = cursor.fetchone()[0]
            
            if not table_exists:
                print(f"⚠️  Expected table {expected_table} does not exist, skipping field alteration")
                return
                
    except Exception as e:
        print(f"⚠️  Error checking table existence: {e}, will attempt migration anyway")


class Migration(migrations.Migration):

    dependencies = [
        ('sms_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(safe_alter_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(help_text='شماره موبایل برای ارسال پیامک (الزامی)', max_length=20, validators=[sms_newsletter.models.validate_iranian_mobile], verbose_name='شماره موبایل'),
        ),
    ]
