# Generated by Django 5.2.7 on 2025-12-25 12:57

import sms_newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(help_text='شماره موبایل برای ارسال پیامک (الزامی)', max_length=20, validators=[sms_newsletter.models.validate_iranian_mobile], verbose_name='شماره موبایل'),
        ),
    ]
