# Generated by Django 5.2.7 on 2025-11-21 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0029_label_categories_label_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived chats are hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='chat.ChatParticipant', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product this chat is about (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='products.product')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(help_text='Browser fingerprint or identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='User account linked after registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Session',
                'verbose_name_plural': 'Guest Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='guest_session',
            field=models.ForeignKey(blank=True, help_text='Guest session if chat started anonymously', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='chat.guestsession'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, help_text='Null if sent by guest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('guest_session', models.ForeignKey(blank=True, help_text='Guest session if sent by guest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.guestsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typing Status',
                'verbose_name_plural': 'Typing Statuses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-updated_at'], name='chat_chatro_updated_fe8347_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_id'], name='chat_chatro_room_id_c3a3db_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='chat_chatme_room_id_466ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_chatme_created_888e17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingstatus',
            unique_together={('room', 'user')},
        ),
    ]
