# Generated by Django 4.2.25 on 2025-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_create_department_subcategory'),
    ]

    operations = [
        # Add many-to-many fields to Category
        migrations.AddField(
            model_name='category',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='categories', to='products.department'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='products.subcategory'),
        ),
        
        # Add many-to-many fields to Subcategory
        migrations.AddField(
            model_name='subcategory',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='products.department'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='child_subcategories', to='products.category'),
        ),
    ]
