# Generated by Django 4.2.25 on 2025-10-15 15:53

from django.db import migrations
from django.utils import timezone


def migrate_existing_data(apps, schema_editor):
    """
    Migrate existing categories to subcategories and assign products
    """
    # Get the models
    Category = apps.get_model('products', 'Category')
    Subcategory = apps.get_model('products', 'Subcategory')
    Product = apps.get_model('products', 'Product')
    Department = apps.get_model('products', 'Department')
    
    # Create a default department if it doesn't exist
    default_dept, created = Department.objects.get_or_create(
        name='General',
        defaults={
            'slug': 'general',
            'description': 'Default department for migrated categories',
            'is_active': True,
            'sort_order': 0,
            'created_at': timezone.now(),
            'updated_at': timezone.now(),
        }
    )
    
    # Migrate existing categories to subcategories
    for category in Category.objects.all():
        # Create subcategory from existing category
        subcategory, created = Subcategory.objects.get_or_create(
            name=category.name,
            defaults={
                'slug': category.name.lower().replace(' ', '-').replace('_', '-'),
                'description': category.description or '',
                'is_active': True,
                'sort_order': 0,
                'created_at': timezone.now(),
                'updated_at': timezone.now(),
            }
        )
        
        # Add relationships
        subcategory.departments.add(default_dept)
        
        # Update products to reference the new subcategory
        for product in Product.objects.filter(category=category):
            product.subcategory = subcategory
            product.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_remaining_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_data, reverse_migration),
    ]
