# Generated by Django 4.2.25 on 2025-10-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_migrate_existing_data'),
    ]

    operations = [
        # Make subcategory field required
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory'),
        ),
        
        # Remove old category field from Product
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
