# Generated by Django 4.2.25 on 2025-10-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_primary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='departments',
        ),
    ]
