# Generated by Django 4.2.25 on 2025-10-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier'),
        ('products', '0019_remove_subcategory_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Company/Supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.supplier'),
        ),
    ]
